# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redmine:
    build: .
    #image: docker.io/bitnami/redmine:5
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_SMTP_HOST=smtp-relay.gmail.com
      - REDMINE_SMTP_PORT=587
      - REDMINE_SMTP_USER=redmine@seattlecommunitynetwork.org
      - REDMINE_SMTP_PASSWORD=${REDMINE_SMTP_PASSWORD}
      - REDMINE_IMAP_PASSWORD=${REDMINE_IMAP_PASSWORD}
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
